spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaUserRegistrationTopic: "user-registration-topic"
    kafkaRoomBookingTopic: "room-booking-topic"
    kafkaGroupId: "statistics-group"

logging:
  level:
    org.springframework: INFO
